fix the decision of Filter
MEONMedical/Log4Qt pull request #63
Opened 2021-12-31 03:46 UTC by siyuhong

Hi, 
I think the filter logic is false，now I fixed it. 
And, I add case sensitivity able in Stringmatchfilter.
Please review this code if you have time.

2022-01-01 14:26 UTC, andibacher requested changes

2022-01-01 14:26 UTC, andibacher commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
Why do you think that if the level matches there should be returned NEUTRAL? Wenn the level matches there should be returned ACCEPT!

2022-01-01 14:26 UTC, andibacher commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
That is the log4j documentation of of NEUTRAL, ACCEPT, DENY:
NEUTRAL: This filter is neutral with respect to the log event. The
remaining filters, if any, should be consulted for a final decision.

ACCEPT : The log event must be logged immediately without consulting with
the remaining filters, if any, in the chain. 

DENY: The log event must be dropped immediately without consulting
 with the remaining filters, if any, in the chain.

2022-01-01 14:26 UTC, andibacher commented on src/log4qt/varia/stringmatchfilter.h
> +    void setStringToMatch(const QString &string, Qt::CaseSensitivity cs = Qt::CaseInsensitive);
This is an extensions that can be accepted.

2022-01-01 14:27 UTC, andibacher commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
Unit Test are also failing because of this change.

2022-01-04 01:49 UTC, siyuhong commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
Sorry，I compared the log4j code and you were right. 
But I have a question: it is still append by default when all levelmatchfilter are non-matched (NEUTRAL)
`
    Filter  *filter = mpHeadFilter.data();
    while (filter)
    {
        Filter::Decision decision = filter->decide(event);
        if (decision == Filter::ACCEPT)
            break;
        else if (decision == Filter::DENY)
            return;
        else
            filter = filter->next().data();
    }
    append(event);
`

2022-01-04 08:15 UTC, andibacher requested changes

2022-01-04 08:16 UTC, andibacher commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
I don't know why this is the behavior but it is the same as in log4j 1:

`    Filter f = this.headFilter;
    
    FILTER_LOOP:
    while(f != null) {
      switch(f.decide(event)) {
      case Filter.DENY: return;
      case Filter.ACCEPT: break FILTER_LOOP;
      case Filter.NEUTRAL: f = f.getNext();
      }
    }
    
    this.append(event);  `

2022-01-04 08:40 UTC, siyuhong commented on src/log4qt/varia/levelmatchfilter.cpp
> +            event.level() == mLevelToMatch)
> I don't know why this is the behavior but it is the same as in log4j 1:
> 
> ` Filter f = this.headFilter;
> 
> ```
> FILTER_LOOP:
> while(f != null) {
>   switch(f.decide(event)) {
>   case Filter.DENY: return;
>   case Filter.ACCEPT: break FILTER_LOOP;
>   case Filter.NEUTRAL: f = f.getNext();
>   }
> }
> 
> this.append(event);  `
> ```

OK，Thanks for you reply.

2022-01-04 11:47 UTC, andibacher commented on src/log4qt/varia/stringmatchfilter.h
> +    void setStringToMatch(const QString &string, Qt::CaseSensitivity cs = Qt::CaseInsensitive);
Please extend the test cases to verify CaseSensitivity and CaseInsensitivty of the StringMatchFilter data driven test of the log4qttest. Thanks,

2022-01-05 02:03 UTC, siyuhong commented on src/log4qt/varia/stringmatchfilter.h
> +    void setStringToMatch(const QString &string, Qt::CaseSensitivity cs = Qt::CaseInsensitive);
> 

OK, I have committed code.

2022-01-07 10:45 UTC, merged